//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTester.UniverseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanetGenerationDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO.UtilityDto")]
    [System.SerializableAttribute()]
    public partial class PlanetGenerationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FoodPoorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FoodRichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForceLivingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForceWaterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MineralPoorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MineralRichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MostlyWaterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FoodPoor {
            get {
                return this.FoodPoorField;
            }
            set {
                if ((this.FoodPoorField.Equals(value) != true)) {
                    this.FoodPoorField = value;
                    this.RaisePropertyChanged("FoodPoor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FoodRich {
            get {
                return this.FoodRichField;
            }
            set {
                if ((this.FoodRichField.Equals(value) != true)) {
                    this.FoodRichField = value;
                    this.RaisePropertyChanged("FoodRich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForceLiving {
            get {
                return this.ForceLivingField;
            }
            set {
                if ((this.ForceLivingField.Equals(value) != true)) {
                    this.ForceLivingField = value;
                    this.RaisePropertyChanged("ForceLiving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForceWater {
            get {
                return this.ForceWaterField;
            }
            set {
                if ((this.ForceWaterField.Equals(value) != true)) {
                    this.ForceWaterField = value;
                    this.RaisePropertyChanged("ForceWater");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxX {
            get {
                return this.MaxXField;
            }
            set {
                if ((this.MaxXField.Equals(value) != true)) {
                    this.MaxXField = value;
                    this.RaisePropertyChanged("MaxX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxY {
            get {
                return this.MaxYField;
            }
            set {
                if ((this.MaxYField.Equals(value) != true)) {
                    this.MaxYField = value;
                    this.RaisePropertyChanged("MaxY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinX {
            get {
                return this.MinXField;
            }
            set {
                if ((this.MinXField.Equals(value) != true)) {
                    this.MinXField = value;
                    this.RaisePropertyChanged("MinX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinY {
            get {
                return this.MinYField;
            }
            set {
                if ((this.MinYField.Equals(value) != true)) {
                    this.MinYField = value;
                    this.RaisePropertyChanged("MinY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MineralPoor {
            get {
                return this.MineralPoorField;
            }
            set {
                if ((this.MineralPoorField.Equals(value) != true)) {
                    this.MineralPoorField = value;
                    this.RaisePropertyChanged("MineralPoor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MineralRich {
            get {
                return this.MineralRichField;
            }
            set {
                if ((this.MineralRichField.Equals(value) != true)) {
                    this.MineralRichField = value;
                    this.RaisePropertyChanged("MineralRich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MostlyWater {
            get {
                return this.MostlyWaterField;
            }
            set {
                if ((this.MostlyWaterField.Equals(value) != true)) {
                    this.MostlyWaterField = value;
                    this.RaisePropertyChanged("MostlyWater");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UniverseService.IUniverse")]
    public interface IUniverse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GetUniversePortion", ReplyAction="http://tempuri.org/IUniverse/GetUniversePortionResponse")]
        string GetUniversePortion(string minX, string minY, string maxX, string maxY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GetUniversePortion", ReplyAction="http://tempuri.org/IUniverse/GetUniversePortionResponse")]
        System.Threading.Tasks.Task<string> GetUniversePortionAsync(string minX, string minY, string maxX, string maxY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GeneratePortion", ReplyAction="http://tempuri.org/IUniverse/GeneratePortionResponse")]
        string GeneratePortion(WcfTester.UniverseService.PlanetGenerationDto generationData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GeneratePortion", ReplyAction="http://tempuri.org/IUniverse/GeneratePortionResponse")]
        System.Threading.Tasks.Task<string> GeneratePortionAsync(WcfTester.UniverseService.PlanetGenerationDto generationData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUniverseChannel : WcfTester.UniverseService.IUniverse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniverseClient : System.ServiceModel.ClientBase<WcfTester.UniverseService.IUniverse>, WcfTester.UniverseService.IUniverse {
        
        public UniverseClient() {
        }
        
        public UniverseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniverseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniverseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniverseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUniversePortion(string minX, string minY, string maxX, string maxY) {
            return base.Channel.GetUniversePortion(minX, minY, maxX, maxY);
        }
        
        public System.Threading.Tasks.Task<string> GetUniversePortionAsync(string minX, string minY, string maxX, string maxY) {
            return base.Channel.GetUniversePortionAsync(minX, minY, maxX, maxY);
        }
        
        public string GeneratePortion(WcfTester.UniverseService.PlanetGenerationDto generationData) {
            return base.Channel.GeneratePortion(generationData);
        }
        
        public System.Threading.Tasks.Task<string> GeneratePortionAsync(WcfTester.UniverseService.PlanetGenerationDto generationData) {
            return base.Channel.GeneratePortionAsync(generationData);
        }
    }
}
