//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbandonato.
        /// </summary>
        internal static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attivo.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popolazione attiva impiegata nella produzione di cibo.
        /// </summary>
        internal static string ActivePopOnFoodProduction {
            get {
                return ResourceManager.GetString("ActivePopOnFoodProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popolazione attiva impiegata nella lavorazione di minerali.
        /// </summary>
        internal static string ActivePopOnOreProduction {
            get {
                return ResourceManager.GetString("ActivePopOnOreProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popolazione attiva impiegata nella ricerca.
        /// </summary>
        internal static string ActivePopOnResProduction {
            get {
                return ResourceManager.GetString("ActivePopOnResProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer di puntamento.
        /// </summary>
        internal static string AimingComputer {
            get {
                return ResourceManager.GetString("AimingComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema di puntamento.
        /// </summary>
        internal static string AimingSystem {
            get {
                return ResourceManager.GetString("AimingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema Arma Nave-Pianeta.
        /// </summary>
        internal static string AntiPlanetWeapon {
            get {
                return ResourceManager.GetString("AntiPlanetWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema Arma Nave-Nave.
        /// </summary>
        internal static string AntiShipWeapon {
            get {
                return ResourceManager.GetString("AntiShipWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armate.
        /// </summary>
        internal static string Armies {
            get {
                return ResourceManager.GetString("Armies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corazza.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla fonda.
        /// </summary>
        internal static string AtBay {
            get {
                return ResourceManager.GetString("AtBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica se una nave/flotta è in orbita su un pianeta o in viaggio.
        /// </summary>
        internal static string AtBayHint {
            get {
                return ResourceManager.GetString("AtBayHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosfera Presente.
        /// </summary>
        internal static string AtmospherePresent {
            get {
                return ResourceManager.GetString("AtmospherePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacco.
        /// </summary>
        internal static string Attack {
            get {
                return ResourceManager.GetString("Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bannato.
        /// </summary>
        internal static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armi a raggio.
        /// </summary>
        internal static string Beams {
            get {
                return ResourceManager.GetString("Beams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma a raggio.
        /// </summary>
        internal static string BeamWeapon {
            get {
                return ResourceManager.GetString("BeamWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miglioramento Vita.
        /// </summary>
        internal static string BetterLiving {
            get {
                return ResourceManager.GetString("BetterLiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloccato.
        /// </summary>
        internal static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blu.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombardamento.
        /// </summary>
        internal static string Bombing {
            get {
                return ResourceManager.GetString("Bombing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombe.
        /// </summary>
        internal static string Bombs {
            get {
                return ResourceManager.GetString("Bombs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus a colpire.
        /// </summary>
        internal static string BonusToHit {
            get {
                return ResourceManager.GetString("BonusToHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string BonusType {
            get {
                return ResourceManager.GetString("BonusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Costruzione.
        /// </summary>
        internal static string BuildingQueues {
            get {
                return ResourceManager.GetString("BuildingQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costruzioni.
        /// </summary>
        internal static string Buildings {
            get {
                return ResourceManager.GetString("Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di costruzione.
        /// </summary>
        internal static string BuildingType {
            get {
                return ResourceManager.GetString("BuildingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stiva.
        /// </summary>
        internal static string Bulk {
            get {
                return ResourceManager.GetString("Bulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costruzioni civili.
        /// </summary>
        internal static string CivilBuilding {
            get {
                return ResourceManager.GetString("CivilBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civili.
        /// </summary>
        internal static string Civils {
            get {
                return ResourceManager.GetString("Civils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonizzazione.
        /// </summary>
        internal static string Colonization {
            get {
                return ResourceManager.GetString("Colonization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonizzato.
        /// </summary>
        internal static string Colonized {
            get {
                return ResourceManager.GetString("Colonized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colore.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocità di combattimento.
        /// </summary>
        internal static string CombatSpeed {
            get {
                return ResourceManager.GetString("CombatSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus sulla velocità di combattimento (%).
        /// </summary>
        internal static string CombatSpeedBonus {
            get {
                return ResourceManager.GetString("CombatSpeedBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratto Culturale.
        /// </summary>
        internal static string CulturalTrait {
            get {
                return ResourceManager.GetString("CulturalTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danni.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemi di difesa.
        /// </summary>
        internal static string DefenceBuildings {
            get {
                return ResourceManager.GetString("DefenceBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinazione.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fattp.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nana.
        /// </summary>
        internal static string Dwarf {
            get {
                return ResourceManager.GetString("Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eccentricità.
        /// </summary>
        internal static string Eccentricity {
            get {
                return ResourceManager.GetString("Eccentricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un numero compreso tra 0 ed 1 che misura quanto un orbita si avvicini ad una circonferenza perfetta (valore 1).
        /// </summary>
        internal static string EccentricityHint {
            get {
                return ResourceManager.GetString("EccentricityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contro-contromisure elettroniche.
        /// </summary>
        internal static string ECCM {
            get {
                return ResourceManager.GetString("ECCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contromisure elettroniche.
        /// </summary>
        internal static string ECM {
            get {
                return ResourceManager.GetString("ECM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miglioramento Produttivo.
        /// </summary>
        internal static string EnancheProduction {
            get {
                return ResourceManager.GetString("EnancheProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energia.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Energia.
        /// </summary>
        internal static string EnergyBonus {
            get {
                return ResourceManager.GetString("EnergyBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celle di energia.
        /// </summary>
        internal static string EnergyCell {
            get {
                return ResourceManager.GetString("EnergyCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motori.
        /// </summary>
        internal static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala Macchine.
        /// </summary>
        internal static string EngineRoom {
            get {
                return ResourceManager.GetString("EngineRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiente.
        /// </summary>
        internal static string Enviroment {
            get {
                return ResourceManager.GetString("Enviroment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termine.
        /// </summary>
        internal static string FinishAt {
            get {
                return ResourceManager.GetString("FinishAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Flotte.
        /// </summary>
        internal static string FleetQueues {
            get {
                return ResourceManager.GetString("FleetQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer di volo.
        /// </summary>
        internal static string FlightComputer {
            get {
                return ResourceManager.GetString("FlightComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cibo.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumo Cibo.
        /// </summary>
        internal static string FoodConsumption {
            get {
                return ResourceManager.GetString("FoodConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produzione oraria Cibo.
        /// </summary>
        internal static string FoodProduction {
            get {
                return ResourceManager.GetString("FoodProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struttura.
        /// </summary>
        internal static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazi Disponibili.
        /// </summary>
        internal static string FreeSpaces {
            get {
                return ResourceManager.GetString("FreeSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energia Sviluppata.
        /// </summary>
        internal static string GeneratedEnergy {
            get {
                return ResourceManager.GetString("GeneratedEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generico.
        /// </summary>
        internal static string Generic {
            get {
                return ResourceManager.GetString("Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigante.
        /// </summary>
        internal static string Giant {
            get {
                return ResourceManager.GetString("Giant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravità Comparata.
        /// </summary>
        internal static string GravityCompared {
            get {
                return ResourceManager.GetString("GravityCompared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero che indica la forza di gravità comparata a quella terrestre. Es, 1.3 =1.3 volte la gravità terrestre..
        /// </summary>
        internal static string GravityComparedHint {
            get {
                return ResourceManager.GetString("GravityComparedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grosse Donazioni.
        /// </summary>
        internal static string GreatDonations {
            get {
                return ResourceManager.GetString("GreatDonations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazi terrestri rimasti.
        /// </summary>
        internal static string GroudSpacesLeft {
            get {
                return ResourceManager.GetString("GroudSpacesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terraferma.
        /// </summary>
        internal static string GroundSpaces {
            get {
                return ResourceManager.GetString("GroundSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazi disponibili di terra ferma, destinabili per costruzioni e/o produzione.
        /// </summary>
        internal static string GroundSpacesHint {
            get {
                return ResourceManager.GetString("GroundSpacesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazi terrestri usati.
        /// </summary>
        internal static string GroundUsedSpaces {
            get {
                return ResourceManager.GetString("GroundUsedSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale Spazi abitabili.
        /// </summary>
        internal static string HabitableSpaces {
            get {
                return ResourceManager.GetString("HabitableSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somma degli spazi terrestri e marini.
        /// </summary>
        internal static string HabitableSpacesHint {
            get {
                return ResourceManager.GetString("HabitableSpacesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasse Elevate.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di scafo.
        /// </summary>
        internal static string HullType {
            get {
                return ResourceManager.GetString("HullType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ipergigante.
        /// </summary>
        internal static string Hyper {
            get {
                return ResourceManager.GetString("Hyper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacanza.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Coda.
        /// </summary>
        internal static string InQueue {
            get {
                return ResourceManager.GetString("InQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasione.
        /// </summary>
        internal static string Invasion {
            get {
                return ResourceManager.GetString("Invasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasse Leggere.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testo Messaggio.
        /// </summary>
        internal static string MailBody {
            get {
                return ResourceManager.GetString("MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaggi.
        /// </summary>
        internal static string Mails {
            get {
                return ResourceManager.GetString("Mails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malus a colpire.
        /// </summary>
        internal static string MalusToHit {
            get {
                return ResourceManager.GetString("MalusToHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massa.
        /// </summary>
        internal static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiali.
        /// </summary>
        internal static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matematica.
        /// </summary>
        internal static string Mathematics {
            get {
                return ResourceManager.GetString("Mathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popolazione Massima.
        /// </summary>
        internal static string MaxPopulation {
            get {
                return ResourceManager.GetString("MaxPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Militare.
        /// </summary>
        internal static string Military {
            get {
                return ResourceManager.GetString("Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costruzioni militari.
        /// </summary>
        internal static string MilitaryBuildings {
            get {
                return ResourceManager.GetString("MilitaryBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Missione.
        /// </summary>
        internal static string MissionType {
            get {
                return ResourceManager.GetString("MissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo in Monete.
        /// </summary>
        internal static string MoneyCost {
            get {
                return ResourceManager.GetString("MoneyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo di manutenzione in Monete.
        /// </summary>
        internal static string MoneyMaintenanceCost {
            get {
                return ResourceManager.GetString("MoneyMaintenanceCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generazione Ricchezza.
        /// </summary>
        internal static string MoneyTax {
            get {
                return ResourceManager.GetString("MoneyTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimento.
        /// </summary>
        internal static string Movement {
            get {
                return ResourceManager.GetString("Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasse Normali.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato Ottimale.
        /// </summary>
        internal static string Optimum {
            get {
                return ResourceManager.GetString("Optimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arancione.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli Orbita.
        /// </summary>
        internal static string OrbitDetails {
            get {
                return ResourceManager.GetString("OrbitDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minerali.
        /// </summary>
        internal static string Ore {
            get {
                return ResourceManager.GetString("Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo in Minerali.
        /// </summary>
        internal static string OreCost {
            get {
                return ResourceManager.GetString("OreCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo di manutenzione in Minerali.
        /// </summary>
        internal static string OreMaintenanceCost {
            get {
                return ResourceManager.GetString("OreMaintenanceCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produzione oraria Minerale.
        /// </summary>
        internal static string OreProduction {
            get {
                return ResourceManager.GetString("OreProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malus sulla velocità di combattimento (%).
        /// </summary>
        internal static string PercCombatSpeedMalus {
            get {
                return ResourceManager.GetString("PercCombatSpeedMalus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malus sulla velocità di crociera (%).
        /// </summary>
        internal static string PercTravelSpeedMalus {
            get {
                return ResourceManager.GetString("PercTravelSpeedMalus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo di Rivoluzione.
        /// </summary>
        internal static string PeriodOfRevolution {
            get {
                return ResourceManager.GetString("PeriodOfRevolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo di Rotazione.
        /// </summary>
        internal static string PeriodOfRotation {
            get {
                return ResourceManager.GetString("PeriodOfRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratto Fisico.
        /// </summary>
        internal static string PhisycalTrait {
            get {
                return ResourceManager.GetString("PhisycalTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisica.
        /// </summary>
        internal static string Phisycs {
            get {
                return ResourceManager.GetString("Phisycs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pianeta.
        /// </summary>
        internal static string Planet {
            get {
                return ResourceManager.GetString("Planet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pianeti.
        /// </summary>
        internal static string Planets {
            get {
                return ResourceManager.GetString("Planets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punti Rimasti.
        /// </summary>
        internal static string PointsLeft {
            get {
                return ResourceManager.GetString("PointsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punti Usati.
        /// </summary>
        internal static string PointsUsed {
            get {
                return ResourceManager.GetString("PointsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popolazione.
        /// </summary>
        internal static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crescita Popolazione.
        /// </summary>
        internal static string PopulationGrowth {
            get {
                return ResourceManager.GetString("PopulationGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posizione.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma a Proiettili.
        /// </summary>
        internal static string Projectile {
            get {
                return ResourceManager.GetString("Projectile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protezione.
        /// </summary>
        internal static string Protection {
            get {
                return ResourceManager.GetString("Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danni Assorbibili.
        /// </summary>
        internal static string ProtectionHint {
            get {
                return ResourceManager.GetString("ProtectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus di razza.
        /// </summary>
        internal static string RaceBonus {
            get {
                return ResourceManager.GetString("RaceBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terreni contaminati.
        /// </summary>
        internal static string RadiatedGround {
            get {
                return ResourceManager.GetString("RadiatedGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazi non utilizzabili senza una bonifica e/o opportune protezioni.
        /// </summary>
        internal static string RadiatedHint {
            get {
                return ResourceManager.GetString("RadiatedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mari contaminati.
        /// </summary>
        internal static string RadiatedWater {
            get {
                return ResourceManager.GetString("RadiatedWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pericolo Radiazioni.
        /// </summary>
        internal static string RadiationHazard {
            get {
                return ResourceManager.GetString("RadiationHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queste armi rendono inabitabili tanti spazi di un pianeta, quanti sono i turni di bombardamento.
        /// </summary>
        internal static string RadiationHazardHint {
            get {
                return ResourceManager.GetString("RadiationHazardHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livello di radiazioni.
        /// </summary>
        internal static string RadiationLevel {
            get {
                return ResourceManager.GetString("RadiationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raggio.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razzia.
        /// </summary>
        internal static string Raid {
            get {
                return ResourceManager.GetString("Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomia.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determina quanto lontano una cella di energia, può portare una nave.
        /// </summary>
        internal static string RangeHint {
            get {
                return ResourceManager.GetString("RangeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadenza di tiro.
        /// </summary>
        internal static string RateOfFire {
            get {
                return ResourceManager.GetString("RateOfFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quante volte un arma spara in un round.
        /// </summary>
        internal static string RateOfFireHint {
            get {
                return ResourceManager.GetString("RateOfFireHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raggio di fuoco.
        /// </summary>
        internal static string RayOfFire {
            get {
                return ResourceManager.GetString("RayOfFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distanza entro cui un arma risulta efficace.
        /// </summary>
        internal static string RayOfFireHint {
            get {
                return ResourceManager.GetString("RayOfFireHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A:.
        /// </summary>
        internal static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rossa.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riduzione inquinamento.
        /// </summary>
        internal static string ReducePollution {
            get {
                return ResourceManager.GetString("ReducePollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energia Richiesta.
        /// </summary>
        internal static string RequiredEnergy {
            get {
                return ResourceManager.GetString("RequiredEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerche.
        /// </summary>
        internal static string Researches {
            get {
                return ResourceManager.GetString("Researches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punti Ricerca.
        /// </summary>
        internal static string ResearchPoints {
            get {
                return ResourceManager.GetString("ResearchPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punti ricerca orari.
        /// </summary>
        internal static string ResearchProduction {
            get {
                return ResourceManager.GetString("ResearchProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivolte in atto!.
        /// </summary>
        internal static string Revolt {
            get {
                return ResourceManager.GetString("Revolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anelli Presenti.
        /// </summary>
        internal static string RingsPresent {
            get {
                return ResourceManager.GetString("RingsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alloggi.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema di governo.
        /// </summary>
        internal static string RulingSystem {
            get {
                return ResourceManager.GetString("RulingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpo Celeste.
        /// </summary>
        internal static string Satellite {
            get {
                return ResourceManager.GetString("Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indici Produttivi.
        /// </summary>
        internal static string SatelliteProduction {
            get {
                return ResourceManager.GetString("SatelliteProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpi Celesti.
        /// </summary>
        internal static string Satellites {
            get {
                return ResourceManager.GetString("Satellites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indici Sociali.
        /// </summary>
        internal static string SatelliteSocial {
            get {
                return ResourceManager.GetString("SatelliteSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato Satellite.
        /// </summary>
        internal static string SatelliteStatus {
            get {
                return ResourceManager.GetString("SatelliteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raggio dei rilevatori.
        /// </summary>
        internal static string ScannerRadius {
            get {
                return ResourceManager.GetString("ScannerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus di Rilevazione (%).
        /// </summary>
        internal static string ScannerRelevationBonus {
            get {
                return ResourceManager.GetString("ScannerRelevationBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malus di Rilevazione (%).
        /// </summary>
        internal static string ScannerRelevationMalus {
            get {
                return ResourceManager.GetString("ScannerRelevationMalus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilevatori.
        /// </summary>
        internal static string Scanners {
            get {
                return ResourceManager.GetString("Scanners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punti Costruzioni.
        /// </summary>
        internal static string ScoreConstruction {
            get {
                return ResourceManager.GetString("ScoreConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punti Cultura.
        /// </summary>
        internal static string ScoreCultural {
            get {
                return ResourceManager.GetString("ScoreCultural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punti Militari.
        /// </summary>
        internal static string ScoreMilitary {
            get {
                return ResourceManager.GetString("ScoreMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punti Ricerca.
        /// </summary>
        internal static string ScoreResearch {
            get {
                return ResourceManager.GetString("ScoreResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da:.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scudi.
        /// </summary>
        internal static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componenti Astronavi.
        /// </summary>
        internal static string ShipComponent {
            get {
                return ResourceManager.GetString("ShipComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parti Astronavi.
        /// </summary>
        internal static string ShipFrame {
            get {
                return ResourceManager.GetString("ShipFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piccole Donazioni.
        /// </summary>
        internal static string SmallDonations {
            get {
                return ResourceManager.GetString("SmallDonations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociale.
        /// </summary>
        internal static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingegneria Sociale.
        /// </summary>
        internal static string SocialLiving {
            get {
                return ResourceManager.GetString("SocialLiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratto Sociale.
        /// </summary>
        internal static string SocialTrait {
            get {
                return ResourceManager.GetString("SocialTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazio.
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus sugli spazi occupati (%).
        /// </summary>
        internal static string SpaceBonus {
            get {
                return ResourceManager.GetString("SpaceBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazi Richiesti.
        /// </summary>
        internal static string SpacesNeeded {
            get {
                return ResourceManager.GetString("SpacesNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo Speciale.
        /// </summary>
        internal static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratto Speciale.
        /// </summary>
        internal static string SpecialTrait {
            get {
                return ResourceManager.GetString("SpecialTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spionaggio.
        /// </summary>
        internal static string Spy {
            get {
                return ResourceManager.GetString("Spy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto di Partenza.
        /// </summary>
        internal static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mancanza di cibo!.
        /// </summary>
        internal static string Starvation {
            get {
                return ResourceManager.GetString("Starvation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strutture.
        /// </summary>
        internal static string Structure {
            get {
                return ResourceManager.GetString("Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punti Struttura.
        /// </summary>
        internal static string StructurePoints {
            get {
                return ResourceManager.GetString("StructurePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quanto danno assorbe la struttura prima di distruggersi.
        /// </summary>
        internal static string StructurePointsHint {
            get {
                return ResourceManager.GetString("StructurePointsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sottocategoria.
        /// </summary>
        internal static string SubField {
            get {
                return ResourceManager.GetString("SubField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasse Esagerate.
        /// </summary>
        internal static string Super {
            get {
                return ResourceManager.GetString("Super", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura Superficiale.
        /// </summary>
        internal static string SurfaceTemp {
            get {
                return ResourceManager.GetString("SurfaceTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipologia del sistema.
        /// </summary>
        internal static string SystemType {
            get {
                return ResourceManager.GetString("SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livello Tasse.
        /// </summary>
        internal static string TaxLevel {
            get {
                return ResourceManager.GetString("TaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnologie.
        /// </summary>
        internal static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo Di Completamento.
        /// </summary>
        internal static string TimeToComplete {
            get {
                return ResourceManager.GetString("TimeToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In attesa di Conferma.
        /// </summary>
        internal static string ToConfirm {
            get {
                return ResourceManager.GetString("ToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sottosistemi.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensioni.
        /// </summary>
        internal static string TotalSpaces {
            get {
                return ResourceManager.GetString("TotalSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rappresenta il numero di spazi totali.
        /// </summary>
        internal static string TotalSpacesHint {
            get {
                return ResourceManager.GetString("TotalSpacesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di Tratto.
        /// </summary>
        internal static string TraitType {
            get {
                return ResourceManager.GetString("TraitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasporto.
        /// </summary>
        internal static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocità di crociera.
        /// </summary>
        internal static string TravelSpeed {
            get {
                return ResourceManager.GetString("TravelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus sulla velocità di crociera (%).
        /// </summary>
        internal static string TravelSpeedBonus {
            get {
                return ResourceManager.GetString("TravelSpeedBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Colonizzabile.
        /// </summary>
        internal static string Uncolonizable {
            get {
                return ResourceManager.GetString("Uncolonizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Colonizzato.
        /// </summary>
        internal static string Uncolonized {
            get {
                return ResourceManager.GetString("Uncolonized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazi Utilizzati.
        /// </summary>
        internal static string UsedSpaces {
            get {
                return ResourceManager.GetString("UsedSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immagine Personale.
        /// </summary>
        internal static string UserImg {
            get {
                return ResourceManager.GetString("UserImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Utente.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato Utente.
        /// </summary>
        internal static string UserStatus {
            get {
                return ResourceManager.GetString("UserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valore.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceani.
        /// </summary>
        internal static string WaterSpaces {
            get {
                return ResourceManager.GetString("WaterSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazi occupati da Acqua, destinabili per costruzioni e/o produzione, soltanto per le razze acquatiche..
        /// </summary>
        internal static string WaterSpacesHint {
            get {
                return ResourceManager.GetString("WaterSpacesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazi marini utilizzabili rimasti.
        /// </summary>
        internal static string WaterSpacesLeft {
            get {
                return ResourceManager.GetString("WaterSpacesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazi marini usati.
        /// </summary>
        internal static string WaterUsedSpaces {
            get {
                return ResourceManager.GetString("WaterUsedSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armi.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bianca.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gialla.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
