namespace DAL.Operations
{
    public enum MappedRepositories
    {
        AntiPlanetWeaponRepository,
        AntiShipWeaponRepository,
        ShipSystemRepository,
        ShieldRepository,
        HullRepository,
        EngineRepository,
        ArmorRepository,
        ShipClassRepository,
        FleetRepository,
        BuildingSpecRepository,
        BuildingRepository,
        GalaxyLogRepository,
        UserLogRepository,
        BuildingQueueRepository,
        FleetQueueRepository,
        ResearchQueueRepository,
        RaceBonusRepository,
        TechNodesRepository,
        TechnologyRepository,
        TechBonusRepository,
        InternalMailRepository,
        PlanetRepository,
        SatelliteRepository,
        StarRepository,
        GalaxyRepository,
        UserRepository
    }
}