//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd2015MVC.BackEndWcf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackEndWcf.IUniverse")]
    public interface IUniverse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveUniversePortion", ReplyAction="http://tempuri.org/IUniverse/RetrieveUniversePortionResponse")]
        string RetrieveUniversePortion(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveUniversePortion", ReplyAction="http://tempuri.org/IUniverse/RetrieveUniversePortionResponse")]
        System.Threading.Tasks.Task<string> RetrieveUniversePortionAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrievePlanetInfo", ReplyAction="http://tempuri.org/IUniverse/RetrievePlanetInfoResponse")]
        string RetrievePlanetInfo(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrievePlanetInfo", ReplyAction="http://tempuri.org/IUniverse/RetrievePlanetInfoResponse")]
        System.Threading.Tasks.Task<string> RetrievePlanetInfoAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveUniverseList", ReplyAction="http://tempuri.org/IUniverse/RetrieveUniverseListResponse")]
        string RetrieveUniverseList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveUniverseList", ReplyAction="http://tempuri.org/IUniverse/RetrieveUniverseListResponse")]
        System.Threading.Tasks.Task<string> RetrieveUniverseListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GenerateStarSystem", ReplyAction="http://tempuri.org/IUniverse/GenerateStarSystemResponse")]
        string GenerateStarSystem(SharedDto.UtilityDto.PlanetGenerationDto generationData, string hashcall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GenerateStarSystem", ReplyAction="http://tempuri.org/IUniverse/GenerateStarSystemResponse")]
        System.Threading.Tasks.Task<string> GenerateStarSystemAsync(SharedDto.UtilityDto.PlanetGenerationDto generationData, string hashcall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/CheckUserRegistration", ReplyAction="http://tempuri.org/IUniverse/CheckUserRegistrationResponse")]
        bool CheckUserRegistration(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/CheckUserRegistration", ReplyAction="http://tempuri.org/IUniverse/CheckUserRegistrationResponse")]
        System.Threading.Tasks.Task<bool> CheckUserRegistrationAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/ServiceTime", ReplyAction="http://tempuri.org/IUniverse/ServiceTimeResponse")]
        string ServiceTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/ServiceTime", ReplyAction="http://tempuri.org/IUniverse/ServiceTimeResponse")]
        System.Threading.Tasks.Task<string> ServiceTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUniverseChannel : FrontEnd2015MVC.BackEndWcf.IUniverse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniverseClient : System.ServiceModel.ClientBase<FrontEnd2015MVC.BackEndWcf.IUniverse>, FrontEnd2015MVC.BackEndWcf.IUniverse {
        
        public UniverseClient() {
        }
        
        public UniverseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniverseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniverseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniverseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RetrieveUniversePortion(string data) {
            return base.Channel.RetrieveUniversePortion(data);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveUniversePortionAsync(string data) {
            return base.Channel.RetrieveUniversePortionAsync(data);
        }
        
        public string RetrievePlanetInfo(string data) {
            return base.Channel.RetrievePlanetInfo(data);
        }
        
        public System.Threading.Tasks.Task<string> RetrievePlanetInfoAsync(string data) {
            return base.Channel.RetrievePlanetInfoAsync(data);
        }
        
        public string RetrieveUniverseList() {
            return base.Channel.RetrieveUniverseList();
        }
        
        public System.Threading.Tasks.Task<string> RetrieveUniverseListAsync() {
            return base.Channel.RetrieveUniverseListAsync();
        }
        
        public string GenerateStarSystem(SharedDto.UtilityDto.PlanetGenerationDto generationData, string hashcall) {
            return base.Channel.GenerateStarSystem(generationData, hashcall);
        }
        
        public System.Threading.Tasks.Task<string> GenerateStarSystemAsync(SharedDto.UtilityDto.PlanetGenerationDto generationData, string hashcall) {
            return base.Channel.GenerateStarSystemAsync(generationData, hashcall);
        }
        
        public bool CheckUserRegistration(string data) {
            return base.Channel.CheckUserRegistration(data);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserRegistrationAsync(string data) {
            return base.Channel.CheckUserRegistrationAsync(data);
        }
        
        public string ServiceTime() {
            return base.Channel.ServiceTime();
        }
        
        public System.Threading.Tasks.Task<string> ServiceTimeAsync() {
            return base.Channel.ServiceTimeAsync();
        }
    }
}
