
namespace Models.Tech.Enum
{
    public enum BonusType
    {
        /*
         *  self::ATTACKBONUS=>Yii::t('pageBody', 'Bonus Attacco'),
            self::DEFENCEBONUS=>Yii::t('pageBody', 'Bonus Difesa'),
            self::ROFBONUS=>Yii::t('pageBody', 'Bonus Velocità di tiro'),
            self::SPEEDBONUS=>Yii::t('pageBody', 'Bonus Velocità'),
            self::ENERGYBONUS=>Yii::t('pageBody', 'Bonus Energia'),
            self::RESEARCHBONUS=>Yii::t('pageBody', 'Bonus Ricerca'),
            self::POPULATIONBONUS=>Yii::t('pageBody', 'Bonus Popolazione'),
            self::TAXBONUS=>Yii::t('pageBody', 'Bonus Tasse'),
            self::SOCIALBONUS=>Yii::t('pageBody', 'Bonus Sociale'),
            self::ARMORBONUS=>Yii::t('pageBody', 'Bonus Armatura'),
            self::FOODBONUS=>Yii::t('pageBody', 'Bonus Cibo'),
            self::PLANETTYPEALLOWED=>Yii::t('pageBody', 'Pianeta Colonizzabile'),
            self::RANGE=>Yii::t('pageBody', 'Raggio'),
            self::SCANNER_RANGE=>Yii::t('pageBody', 'Raggio Scanners'),
            self::SHIELD_BONUS=>Yii::t('pageBody', 'Bonus Scudi'),
            self::ORE_BONUS=>Yii::t('pageBody', 'Bonus Produzione Minerali'),
            self::GOLD_BONUS=>Yii::t('pageBody', 'Bonus Produzione oro'),
            self::MAINT_BONUS=>Yii::t('pageBody', 'Bonus Riduzione Costi'),
            self::SPACE=>Yii::t('pageBody', 'Spazi'),
            self::ARMOPIERCINGFACTOR=>Yii::t('pageBody', 'Fattore Penetrazione Armatura'),
            self::TERRAFORMFACTOR=>Yii::t('pageBody', 'Fattore Terraforming'),
            self::SPATIALCOMPRESSIONFACTOR=>Yii::t('pageBody', 'Fattore Compressione'),
            self::BATTLESPEEDBONUS=>Yii::t('pageBody', 'Bonus Velocità di Combattimento'),
            self::PREREQUISITO=>Yii::t('pageBody', 'Prerequisito'),
            self::BONUSTIMETOBUILD=>Yii::t('pageBody', 'Bonus Tempo Costruzione'),
            self::SPYINGBONUS=>Yii::t('pageBody', 'Bonus Spionaggio'),
            self::PRECISIONBONUS=>Yii::t('pageBody', 'Bonus Precisione'),
         */
        ATTACKBONUS,
        DEFENCEBONUS ,
        ROFBONUS,
        SPEEDBONUS ,
        ENERGYBONUS ,
        RESEARCHBONUS,
        POPULATIONBONUS ,
        TAXBONUS,
        SOCIALBONUS,
        ARMORBONUS ,
        FOODBONUS,
        PLANETTYPEALLOWED,
        RANGE,
        SCANNER_RANGE,
        SHIELD_BONUS,
        ORE_BONUS,
        GOLD_BONUS,
        MAINT_BONUS,
        SPACE,
        ARMOPIERCINGFACTOR,
        TERRAFORMFACTOR,
        SPATIALCOMPRESSIONFACTOR,
        BATTLESPEEDBONUS,
        PREREQUISITO,
        BONUSTIMETOBUILD,
        SPYINGBONUS,
        PRECISIONBONUS,

    }
}
