using System.Runtime.Serialization;
namespace Models.Tech.Enum
{
    [DataContract]
    public enum BonusType
    {
        [EnumMember]
        ATTACKBONUS,
        [EnumMember]
        DEFENCEBONUS,
        [EnumMember]
        ROFBONUS,
        SPEEDBONUS,
        [EnumMember]
        ENERGYBONUS,
        [EnumMember]
        RESEARCHBONUS,
        [EnumMember]
        POPULATIONBONUS,
        [EnumMember]
        TAXBONUS,
        [EnumMember]
        SOCIALBONUS,
        [EnumMember]
        ARMORBONUS,
        [EnumMember]
        FOODBONUS,
        [EnumMember]
        PLANETTYPEALLOWED,
        [EnumMember]
        RANGE,
        [EnumMember]
        SCANNER_RANGE,
        [EnumMember]
        SHIELD_BONUS,
        [EnumMember]
        ORE_BONUS,
        [EnumMember]
        GOLD_BONUS,
        [EnumMember]
        MAINT_BONUS,
        [EnumMember]
        SPACE,
        [EnumMember]
        ARMOPIERCINGFACTOR,
        [EnumMember]
        TERRAFORMFACTOR,
        [EnumMember]
        SPATIALCOMPRESSIONFACTOR,
        [EnumMember]
        BATTLESPEEDBONUS,
        [EnumMember]
        PREREQUISITO,
        [EnumMember]
        BONUSTIMETOBUILD,
        [EnumMember]
        SPYINGBONUS,
        [EnumMember]
        PRECISIONBONUS,

    }
}