//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTester.UninverseWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrievingInfoDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO.UtilityDto")]
    [System.SerializableAttribute()]
    public partial class RetrievingInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTester.UninverseWcf.BaseAuthDto AuthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTester.UninverseWcf.BaseAuthDto Auth {
            get {
                return this.AuthField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthField, value) != true)) {
                    this.AuthField = value;
                    this.RaisePropertyChanged("Auth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAuthDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO")]
    [System.SerializableAttribute()]
    public partial class BaseAuthDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthHash_01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthHash_02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GeneratedStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthHash_01 {
            get {
                return this.AuthHash_01Field;
            }
            set {
                if ((object.ReferenceEquals(this.AuthHash_01Field, value) != true)) {
                    this.AuthHash_01Field = value;
                    this.RaisePropertyChanged("AuthHash_01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthHash_02 {
            get {
                return this.AuthHash_02Field;
            }
            set {
                if ((object.ReferenceEquals(this.AuthHash_02Field, value) != true)) {
                    this.AuthHash_02Field = value;
                    this.RaisePropertyChanged("AuthHash_02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GeneratedStamp {
            get {
                return this.GeneratedStampField;
            }
            set {
                if ((this.GeneratedStampField.Equals(value) != true)) {
                    this.GeneratedStampField = value;
                    this.RaisePropertyChanged("GeneratedStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniverseRangeDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO.UtilityDto")]
    [System.SerializableAttribute()]
    public partial class UniverseRangeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTester.UninverseWcf.BaseAuthDto AuthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTester.UninverseWcf.BaseAuthDto Auth {
            get {
                return this.AuthField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthField, value) != true)) {
                    this.AuthField = value;
                    this.RaisePropertyChanged("Auth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxX {
            get {
                return this.MaxXField;
            }
            set {
                if ((this.MaxXField.Equals(value) != true)) {
                    this.MaxXField = value;
                    this.RaisePropertyChanged("MaxX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxY {
            get {
                return this.MaxYField;
            }
            set {
                if ((this.MaxYField.Equals(value) != true)) {
                    this.MaxYField = value;
                    this.RaisePropertyChanged("MaxY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinX {
            get {
                return this.MinXField;
            }
            set {
                if ((this.MinXField.Equals(value) != true)) {
                    this.MinXField = value;
                    this.RaisePropertyChanged("MinX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinY {
            get {
                return this.MinYField;
            }
            set {
                if ((this.MinYField.Equals(value) != true)) {
                    this.MinYField = value;
                    this.RaisePropertyChanged("MinY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanetGenerationDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO.UtilityDto")]
    [System.SerializableAttribute()]
    public partial class PlanetGenerationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FoodPoorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FoodRichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForceLivingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForceWaterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Galaxy_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MineralPoorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MineralRichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MostlyWaterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FoodPoor {
            get {
                return this.FoodPoorField;
            }
            set {
                if ((this.FoodPoorField.Equals(value) != true)) {
                    this.FoodPoorField = value;
                    this.RaisePropertyChanged("FoodPoor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FoodRich {
            get {
                return this.FoodRichField;
            }
            set {
                if ((this.FoodRichField.Equals(value) != true)) {
                    this.FoodRichField = value;
                    this.RaisePropertyChanged("FoodRich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForceLiving {
            get {
                return this.ForceLivingField;
            }
            set {
                if ((this.ForceLivingField.Equals(value) != true)) {
                    this.ForceLivingField = value;
                    this.RaisePropertyChanged("ForceLiving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForceWater {
            get {
                return this.ForceWaterField;
            }
            set {
                if ((this.ForceWaterField.Equals(value) != true)) {
                    this.ForceWaterField = value;
                    this.RaisePropertyChanged("ForceWater");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Galaxy_Id {
            get {
                return this.Galaxy_IdField;
            }
            set {
                if ((this.Galaxy_IdField.Equals(value) != true)) {
                    this.Galaxy_IdField = value;
                    this.RaisePropertyChanged("Galaxy_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxX {
            get {
                return this.MaxXField;
            }
            set {
                if ((this.MaxXField.Equals(value) != true)) {
                    this.MaxXField = value;
                    this.RaisePropertyChanged("MaxX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxY {
            get {
                return this.MaxYField;
            }
            set {
                if ((this.MaxYField.Equals(value) != true)) {
                    this.MaxYField = value;
                    this.RaisePropertyChanged("MaxY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinX {
            get {
                return this.MinXField;
            }
            set {
                if ((this.MinXField.Equals(value) != true)) {
                    this.MinXField = value;
                    this.RaisePropertyChanged("MinX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinY {
            get {
                return this.MinYField;
            }
            set {
                if ((this.MinYField.Equals(value) != true)) {
                    this.MinYField = value;
                    this.RaisePropertyChanged("MinY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MineralPoor {
            get {
                return this.MineralPoorField;
            }
            set {
                if ((this.MineralPoorField.Equals(value) != true)) {
                    this.MineralPoorField = value;
                    this.RaisePropertyChanged("MineralPoor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MineralRich {
            get {
                return this.MineralRichField;
            }
            set {
                if ((this.MineralRichField.Equals(value) != true)) {
                    this.MineralRichField = value;
                    this.RaisePropertyChanged("MineralRich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MostlyWater {
            get {
                return this.MostlyWaterField;
            }
            set {
                if ((this.MostlyWaterField.Equals(value) != true)) {
                    this.MostlyWaterField = value;
                    this.RaisePropertyChanged("MostlyWater");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UninverseWcf.IUniverse")]
    public interface IUniverse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveUniversePortion", ReplyAction="http://tempuri.org/IUniverse/RetrieveUniversePortionResponse")]
        string RetrieveUniversePortion(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveUniversePortion", ReplyAction="http://tempuri.org/IUniverse/RetrieveUniversePortionResponse")]
        System.Threading.Tasks.Task<string> RetrieveUniversePortionAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrievePlanetInfo", ReplyAction="http://tempuri.org/IUniverse/RetrievePlanetInfoResponse")]
        string RetrievePlanetInfo(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrievePlanetInfo", ReplyAction="http://tempuri.org/IUniverse/RetrievePlanetInfoResponse")]
        System.Threading.Tasks.Task<string> RetrievePlanetInfoAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveInfoUnused", ReplyAction="http://tempuri.org/IUniverse/RetrieveInfoUnusedResponse")]
        string RetrieveInfoUnused(WcfTester.UninverseWcf.RetrievingInfoDto data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveInfoUnused", ReplyAction="http://tempuri.org/IUniverse/RetrieveInfoUnusedResponse")]
        System.Threading.Tasks.Task<string> RetrieveInfoUnusedAsync(WcfTester.UninverseWcf.RetrievingInfoDto data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveUniversePortionUnused", ReplyAction="http://tempuri.org/IUniverse/RetrieveUniversePortionUnusedResponse")]
        string RetrieveUniversePortionUnused(WcfTester.UninverseWcf.UniverseRangeDto data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveUniversePortionUnused", ReplyAction="http://tempuri.org/IUniverse/RetrieveUniversePortionUnusedResponse")]
        System.Threading.Tasks.Task<string> RetrieveUniversePortionUnusedAsync(WcfTester.UninverseWcf.UniverseRangeDto data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GenerateStarSystem", ReplyAction="http://tempuri.org/IUniverse/GenerateStarSystemResponse")]
        string GenerateStarSystem(WcfTester.UninverseWcf.PlanetGenerationDto generationData, string hashcall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GenerateStarSystem", ReplyAction="http://tempuri.org/IUniverse/GenerateStarSystemResponse")]
        System.Threading.Tasks.Task<string> GenerateStarSystemAsync(WcfTester.UninverseWcf.PlanetGenerationDto generationData, string hashcall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/ServiceTime", ReplyAction="http://tempuri.org/IUniverse/ServiceTimeResponse")]
        string ServiceTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/ServiceTime", ReplyAction="http://tempuri.org/IUniverse/ServiceTimeResponse")]
        System.Threading.Tasks.Task<string> ServiceTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUniverseChannel : WcfTester.UninverseWcf.IUniverse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniverseClient : System.ServiceModel.ClientBase<WcfTester.UninverseWcf.IUniverse>, WcfTester.UninverseWcf.IUniverse {
        
        public UniverseClient() {
        }
        
        public UniverseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniverseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniverseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniverseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RetrieveUniversePortion(string data) {
            return base.Channel.RetrieveUniversePortion(data);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveUniversePortionAsync(string data) {
            return base.Channel.RetrieveUniversePortionAsync(data);
        }
        
        public string RetrievePlanetInfo(string data) {
            return base.Channel.RetrievePlanetInfo(data);
        }
        
        public System.Threading.Tasks.Task<string> RetrievePlanetInfoAsync(string data) {
            return base.Channel.RetrievePlanetInfoAsync(data);
        }
        
        public string RetrieveInfoUnused(WcfTester.UninverseWcf.RetrievingInfoDto data) {
            return base.Channel.RetrieveInfoUnused(data);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveInfoUnusedAsync(WcfTester.UninverseWcf.RetrievingInfoDto data) {
            return base.Channel.RetrieveInfoUnusedAsync(data);
        }
        
        public string RetrieveUniversePortionUnused(WcfTester.UninverseWcf.UniverseRangeDto data) {
            return base.Channel.RetrieveUniversePortionUnused(data);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveUniversePortionUnusedAsync(WcfTester.UninverseWcf.UniverseRangeDto data) {
            return base.Channel.RetrieveUniversePortionUnusedAsync(data);
        }
        
        public string GenerateStarSystem(WcfTester.UninverseWcf.PlanetGenerationDto generationData, string hashcall) {
            return base.Channel.GenerateStarSystem(generationData, hashcall);
        }
        
        public System.Threading.Tasks.Task<string> GenerateStarSystemAsync(WcfTester.UninverseWcf.PlanetGenerationDto generationData, string hashcall) {
            return base.Channel.GenerateStarSystemAsync(generationData, hashcall);
        }
        
        public string ServiceTime() {
            return base.Channel.ServiceTime();
        }
        
        public System.Threading.Tasks.Task<string> ServiceTimeAsync() {
            return base.Channel.ServiceTimeAsync();
        }
    }
}
