//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTester.UninverseWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniverseRangeDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO.UtilityDto")]
    [System.SerializableAttribute()]
    public partial class UniverseRangeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTester.UninverseWcf.BaseAuthDto AuthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTester.UninverseWcf.BaseAuthDto Auth {
            get {
                return this.AuthField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthField, value) != true)) {
                    this.AuthField = value;
                    this.RaisePropertyChanged("Auth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxX {
            get {
                return this.MaxXField;
            }
            set {
                if ((this.MaxXField.Equals(value) != true)) {
                    this.MaxXField = value;
                    this.RaisePropertyChanged("MaxX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxY {
            get {
                return this.MaxYField;
            }
            set {
                if ((this.MaxYField.Equals(value) != true)) {
                    this.MaxYField = value;
                    this.RaisePropertyChanged("MaxY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinX {
            get {
                return this.MinXField;
            }
            set {
                if ((this.MinXField.Equals(value) != true)) {
                    this.MinXField = value;
                    this.RaisePropertyChanged("MinX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinY {
            get {
                return this.MinYField;
            }
            set {
                if ((this.MinYField.Equals(value) != true)) {
                    this.MinYField = value;
                    this.RaisePropertyChanged("MinY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAuthDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO")]
    [System.SerializableAttribute()]
    public partial class BaseAuthDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GeneratedStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthHash {
            get {
                return this.AuthHashField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthHashField, value) != true)) {
                    this.AuthHashField = value;
                    this.RaisePropertyChanged("AuthHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GeneratedStamp {
            get {
                return this.GeneratedStampField;
            }
            set {
                if ((this.GeneratedStampField.Equals(value) != true)) {
                    this.GeneratedStampField = value;
                    this.RaisePropertyChanged("GeneratedStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StarDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO.Universe")]
    [System.SerializableAttribute()]
    public partial class StarDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GalaxyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTester.UninverseWcf.PlanetDto[] PlanetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositgionYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RadiationLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RadiusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StarColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StarTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurfaceTempField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GalaxyId {
            get {
                return this.GalaxyIdField;
            }
            set {
                if ((this.GalaxyIdField.Equals(value) != true)) {
                    this.GalaxyIdField = value;
                    this.RaisePropertyChanged("GalaxyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mass {
            get {
                return this.MassField;
            }
            set {
                if ((this.MassField.Equals(value) != true)) {
                    this.MassField = value;
                    this.RaisePropertyChanged("Mass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTester.UninverseWcf.PlanetDto[] Planets {
            get {
                return this.PlanetsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanetsField, value) != true)) {
                    this.PlanetsField = value;
                    this.RaisePropertyChanged("Planets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositgionY {
            get {
                return this.PositgionYField;
            }
            set {
                if ((this.PositgionYField.Equals(value) != true)) {
                    this.PositgionYField = value;
                    this.RaisePropertyChanged("PositgionY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionX {
            get {
                return this.PositionXField;
            }
            set {
                if ((this.PositionXField.Equals(value) != true)) {
                    this.PositionXField = value;
                    this.RaisePropertyChanged("PositionX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RadiationLevel {
            get {
                return this.RadiationLevelField;
            }
            set {
                if ((this.RadiationLevelField.Equals(value) != true)) {
                    this.RadiationLevelField = value;
                    this.RaisePropertyChanged("RadiationLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Radius {
            get {
                return this.RadiusField;
            }
            set {
                if ((this.RadiusField.Equals(value) != true)) {
                    this.RadiusField = value;
                    this.RaisePropertyChanged("Radius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StarColor {
            get {
                return this.StarColorField;
            }
            set {
                if ((object.ReferenceEquals(this.StarColorField, value) != true)) {
                    this.StarColorField = value;
                    this.RaisePropertyChanged("StarColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StarType {
            get {
                return this.StarTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StarTypeField, value) != true)) {
                    this.StarTypeField = value;
                    this.RaisePropertyChanged("StarType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurfaceTemp {
            get {
                return this.SurfaceTempField;
            }
            set {
                if ((this.SurfaceTempField.Equals(value) != true)) {
                    this.SurfaceTempField = value;
                    this.RaisePropertyChanged("SurfaceTemp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanetDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO.Universe")]
    [System.SerializableAttribute()]
    public partial class PlanetDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ActivePopOnFoodProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ActivePopOnOreProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ActivePopOnResProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtmospherePresentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTester.UninverseWcf.BuildingDto[] BuildingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DistanceRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EccentricityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FoodProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GravityEarthComparedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroundRadiatedSpacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroundSpacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroundSpacesLeftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroundUsedSpacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HabitableSpacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPopulationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OreProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PeriodOfRevolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PeriodOfRotationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PopulationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RadiationLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RadiusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResearchPointProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RingsPresentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTester.UninverseWcf.SatelliteStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurfaceTempField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTester.UninverseWcf.TaxLevel TaxLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TetaZeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalspacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WaterRadiatedSpacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WaterSpacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WaterSpacesLeftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WaterUsedSpacesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ActivePopOnFoodProduction {
            get {
                return this.ActivePopOnFoodProductionField;
            }
            set {
                if ((this.ActivePopOnFoodProductionField.Equals(value) != true)) {
                    this.ActivePopOnFoodProductionField = value;
                    this.RaisePropertyChanged("ActivePopOnFoodProduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ActivePopOnOreProduction {
            get {
                return this.ActivePopOnOreProductionField;
            }
            set {
                if ((this.ActivePopOnOreProductionField.Equals(value) != true)) {
                    this.ActivePopOnOreProductionField = value;
                    this.RaisePropertyChanged("ActivePopOnOreProduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ActivePopOnResProduction {
            get {
                return this.ActivePopOnResProductionField;
            }
            set {
                if ((this.ActivePopOnResProductionField.Equals(value) != true)) {
                    this.ActivePopOnResProductionField = value;
                    this.RaisePropertyChanged("ActivePopOnResProduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AtmospherePresent {
            get {
                return this.AtmospherePresentField;
            }
            set {
                if ((this.AtmospherePresentField.Equals(value) != true)) {
                    this.AtmospherePresentField = value;
                    this.RaisePropertyChanged("AtmospherePresent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTester.UninverseWcf.BuildingDto[] Buildings {
            get {
                return this.BuildingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingsField, value) != true)) {
                    this.BuildingsField = value;
                    this.RaisePropertyChanged("Buildings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DistanceR {
            get {
                return this.DistanceRField;
            }
            set {
                if ((this.DistanceRField.Equals(value) != true)) {
                    this.DistanceRField = value;
                    this.RaisePropertyChanged("DistanceR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Eccentricity {
            get {
                return this.EccentricityField;
            }
            set {
                if ((this.EccentricityField.Equals(value) != true)) {
                    this.EccentricityField = value;
                    this.RaisePropertyChanged("Eccentricity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FoodProduction {
            get {
                return this.FoodProductionField;
            }
            set {
                if ((this.FoodProductionField.Equals(value) != true)) {
                    this.FoodProductionField = value;
                    this.RaisePropertyChanged("FoodProduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GravityEarthCompared {
            get {
                return this.GravityEarthComparedField;
            }
            set {
                if ((this.GravityEarthComparedField.Equals(value) != true)) {
                    this.GravityEarthComparedField = value;
                    this.RaisePropertyChanged("GravityEarthCompared");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroundRadiatedSpaces {
            get {
                return this.GroundRadiatedSpacesField;
            }
            set {
                if ((this.GroundRadiatedSpacesField.Equals(value) != true)) {
                    this.GroundRadiatedSpacesField = value;
                    this.RaisePropertyChanged("GroundRadiatedSpaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroundSpaces {
            get {
                return this.GroundSpacesField;
            }
            set {
                if ((this.GroundSpacesField.Equals(value) != true)) {
                    this.GroundSpacesField = value;
                    this.RaisePropertyChanged("GroundSpaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroundSpacesLeft {
            get {
                return this.GroundSpacesLeftField;
            }
            set {
                if ((this.GroundSpacesLeftField.Equals(value) != true)) {
                    this.GroundSpacesLeftField = value;
                    this.RaisePropertyChanged("GroundSpacesLeft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroundUsedSpaces {
            get {
                return this.GroundUsedSpacesField;
            }
            set {
                if ((this.GroundUsedSpacesField.Equals(value) != true)) {
                    this.GroundUsedSpacesField = value;
                    this.RaisePropertyChanged("GroundUsedSpaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HabitableSpaces {
            get {
                return this.HabitableSpacesField;
            }
            set {
                if ((this.HabitableSpacesField.Equals(value) != true)) {
                    this.HabitableSpacesField = value;
                    this.RaisePropertyChanged("HabitableSpaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mass {
            get {
                return this.MassField;
            }
            set {
                if ((this.MassField.Equals(value) != true)) {
                    this.MassField = value;
                    this.RaisePropertyChanged("Mass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPopulation {
            get {
                return this.MaxPopulationField;
            }
            set {
                if ((this.MaxPopulationField.Equals(value) != true)) {
                    this.MaxPopulationField = value;
                    this.RaisePropertyChanged("MaxPopulation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OreProduction {
            get {
                return this.OreProductionField;
            }
            set {
                if ((this.OreProductionField.Equals(value) != true)) {
                    this.OreProductionField = value;
                    this.RaisePropertyChanged("OreProduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PeriodOfRevolution {
            get {
                return this.PeriodOfRevolutionField;
            }
            set {
                if ((this.PeriodOfRevolutionField.Equals(value) != true)) {
                    this.PeriodOfRevolutionField = value;
                    this.RaisePropertyChanged("PeriodOfRevolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PeriodOfRotation {
            get {
                return this.PeriodOfRotationField;
            }
            set {
                if ((this.PeriodOfRotationField.Equals(value) != true)) {
                    this.PeriodOfRotationField = value;
                    this.RaisePropertyChanged("PeriodOfRotation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RadiationLevel {
            get {
                return this.RadiationLevelField;
            }
            set {
                if ((this.RadiationLevelField.Equals(value) != true)) {
                    this.RadiationLevelField = value;
                    this.RaisePropertyChanged("RadiationLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Radius {
            get {
                return this.RadiusField;
            }
            set {
                if ((this.RadiusField.Equals(value) != true)) {
                    this.RadiusField = value;
                    this.RaisePropertyChanged("Radius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResearchPointProduction {
            get {
                return this.ResearchPointProductionField;
            }
            set {
                if ((this.ResearchPointProductionField.Equals(value) != true)) {
                    this.ResearchPointProductionField = value;
                    this.RaisePropertyChanged("ResearchPointProduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RingsPresent {
            get {
                return this.RingsPresentField;
            }
            set {
                if ((this.RingsPresentField.Equals(value) != true)) {
                    this.RingsPresentField = value;
                    this.RaisePropertyChanged("RingsPresent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTester.UninverseWcf.SatelliteStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurfaceTemp {
            get {
                return this.SurfaceTempField;
            }
            set {
                if ((this.SurfaceTempField.Equals(value) != true)) {
                    this.SurfaceTempField = value;
                    this.RaisePropertyChanged("SurfaceTemp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTester.UninverseWcf.TaxLevel TaxLevel {
            get {
                return this.TaxLevelField;
            }
            set {
                if ((this.TaxLevelField.Equals(value) != true)) {
                    this.TaxLevelField = value;
                    this.RaisePropertyChanged("TaxLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TetaZero {
            get {
                return this.TetaZeroField;
            }
            set {
                if ((this.TetaZeroField.Equals(value) != true)) {
                    this.TetaZeroField = value;
                    this.RaisePropertyChanged("TetaZero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Totalspaces {
            get {
                return this.TotalspacesField;
            }
            set {
                if ((this.TotalspacesField.Equals(value) != true)) {
                    this.TotalspacesField = value;
                    this.RaisePropertyChanged("Totalspaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WaterRadiatedSpaces {
            get {
                return this.WaterRadiatedSpacesField;
            }
            set {
                if ((this.WaterRadiatedSpacesField.Equals(value) != true)) {
                    this.WaterRadiatedSpacesField = value;
                    this.RaisePropertyChanged("WaterRadiatedSpaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WaterSpaces {
            get {
                return this.WaterSpacesField;
            }
            set {
                if ((this.WaterSpacesField.Equals(value) != true)) {
                    this.WaterSpacesField = value;
                    this.RaisePropertyChanged("WaterSpaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WaterSpacesLeft {
            get {
                return this.WaterSpacesLeftField;
            }
            set {
                if ((this.WaterSpacesLeftField.Equals(value) != true)) {
                    this.WaterSpacesLeftField = value;
                    this.RaisePropertyChanged("WaterSpacesLeft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WaterUsedSpaces {
            get {
                return this.WaterUsedSpacesField;
            }
            set {
                if ((this.WaterUsedSpacesField.Equals(value) != true)) {
                    this.WaterUsedSpacesField = value;
                    this.RaisePropertyChanged("WaterUsedSpaces");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuildingDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO.Universe")]
    [System.SerializableAttribute()]
    public partial class BuildingDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTester.UninverseWcf.BuildingType BuildingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTester.UninverseWcf.BuildingSpecsDto[] DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MoneyCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MoneyMaintenanceCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OreCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OreMaintenanceCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpaceNeededField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsedSpacesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTester.UninverseWcf.BuildingType BuildingType {
            get {
                return this.BuildingTypeField;
            }
            set {
                if ((this.BuildingTypeField.Equals(value) != true)) {
                    this.BuildingTypeField = value;
                    this.RaisePropertyChanged("BuildingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTester.UninverseWcf.BuildingSpecsDto[] Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MoneyCost {
            get {
                return this.MoneyCostField;
            }
            set {
                if ((this.MoneyCostField.Equals(value) != true)) {
                    this.MoneyCostField = value;
                    this.RaisePropertyChanged("MoneyCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MoneyMaintenanceCost {
            get {
                return this.MoneyMaintenanceCostField;
            }
            set {
                if ((this.MoneyMaintenanceCostField.Equals(value) != true)) {
                    this.MoneyMaintenanceCostField = value;
                    this.RaisePropertyChanged("MoneyMaintenanceCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OreCost {
            get {
                return this.OreCostField;
            }
            set {
                if ((this.OreCostField.Equals(value) != true)) {
                    this.OreCostField = value;
                    this.RaisePropertyChanged("OreCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OreMaintenanceCost {
            get {
                return this.OreMaintenanceCostField;
            }
            set {
                if ((this.OreMaintenanceCostField.Equals(value) != true)) {
                    this.OreMaintenanceCostField = value;
                    this.RaisePropertyChanged("OreMaintenanceCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SpaceNeeded {
            get {
                return this.SpaceNeededField;
            }
            set {
                if ((this.SpaceNeededField.Equals(value) != true)) {
                    this.SpaceNeededField = value;
                    this.RaisePropertyChanged("SpaceNeeded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsedSpaces {
            get {
                return this.UsedSpacesField;
            }
            set {
                if ((this.UsedSpacesField.Equals(value) != true)) {
                    this.UsedSpacesField = value;
                    this.RaisePropertyChanged("UsedSpaces");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="SatelliteStatus", Namespace="http://schemas.datacontract.org/2004/07/Models.Universe.Enum")]
    public enum SatelliteStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uncolonizable = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uncolonized = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Colonized = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Starvation = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Revolt = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Optimum = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Abandoned = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxLevel", Namespace="http://schemas.datacontract.org/2004/07/Models.Base.Enum")]
    public enum TaxLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreatDonations = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmallDonations = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Heavy = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuperHeavy = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuildingType", Namespace="http://schemas.datacontract.org/2004/07/Models.Buildings.Enums")]
    public enum BuildingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Civil = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Military = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CivilInOrbit = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MilitaryInOrbit = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuildingSpecsDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO.Universe")]
    [System.SerializableAttribute()]
    public partial class BuildingSpecsDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTester.UninverseWcf.BonusType BonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTester.UninverseWcf.BonusType Bonus {
            get {
                return this.BonusField;
            }
            set {
                if ((this.BonusField.Equals(value) != true)) {
                    this.BonusField = value;
                    this.RaisePropertyChanged("Bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BonusType", Namespace="http://schemas.datacontract.org/2004/07/Models.Tech.Enum")]
    public enum BonusType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATTACKBONUS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DEFENCEBONUS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROFBONUS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENERGYBONUS = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESEARCHBONUS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        POPULATIONBONUS = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TAXBONUS = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOCIALBONUS = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARMORBONUS = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOODBONUS = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLANETTYPEALLOWED = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RANGE = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCANNER_RANGE = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHIELD_BONUS = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ORE_BONUS = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GOLD_BONUS = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAINT_BONUS = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SPACE = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARMOPIERCINGFACTOR = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TERRAFORMFACTOR = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SPATIALCOMPRESSIONFACTOR = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BATTLESPEEDBONUS = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PREREQUISITO = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BONUSTIMETOBUILD = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SPYINGBONUS = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRECISIONBONUS = 26,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanetGenerationDto", Namespace="http://schemas.datacontract.org/2004/07/_2015ProjectsBackEndWs.DTO.UtilityDto")]
    [System.SerializableAttribute()]
    public partial class PlanetGenerationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FoodPoorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FoodRichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForceLivingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForceWaterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MineralPoorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MineralRichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MostlyWaterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FoodPoor {
            get {
                return this.FoodPoorField;
            }
            set {
                if ((this.FoodPoorField.Equals(value) != true)) {
                    this.FoodPoorField = value;
                    this.RaisePropertyChanged("FoodPoor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FoodRich {
            get {
                return this.FoodRichField;
            }
            set {
                if ((this.FoodRichField.Equals(value) != true)) {
                    this.FoodRichField = value;
                    this.RaisePropertyChanged("FoodRich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForceLiving {
            get {
                return this.ForceLivingField;
            }
            set {
                if ((this.ForceLivingField.Equals(value) != true)) {
                    this.ForceLivingField = value;
                    this.RaisePropertyChanged("ForceLiving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForceWater {
            get {
                return this.ForceWaterField;
            }
            set {
                if ((this.ForceWaterField.Equals(value) != true)) {
                    this.ForceWaterField = value;
                    this.RaisePropertyChanged("ForceWater");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxX {
            get {
                return this.MaxXField;
            }
            set {
                if ((this.MaxXField.Equals(value) != true)) {
                    this.MaxXField = value;
                    this.RaisePropertyChanged("MaxX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxY {
            get {
                return this.MaxYField;
            }
            set {
                if ((this.MaxYField.Equals(value) != true)) {
                    this.MaxYField = value;
                    this.RaisePropertyChanged("MaxY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinX {
            get {
                return this.MinXField;
            }
            set {
                if ((this.MinXField.Equals(value) != true)) {
                    this.MinXField = value;
                    this.RaisePropertyChanged("MinX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinY {
            get {
                return this.MinYField;
            }
            set {
                if ((this.MinYField.Equals(value) != true)) {
                    this.MinYField = value;
                    this.RaisePropertyChanged("MinY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MineralPoor {
            get {
                return this.MineralPoorField;
            }
            set {
                if ((this.MineralPoorField.Equals(value) != true)) {
                    this.MineralPoorField = value;
                    this.RaisePropertyChanged("MineralPoor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MineralRich {
            get {
                return this.MineralRichField;
            }
            set {
                if ((this.MineralRichField.Equals(value) != true)) {
                    this.MineralRichField = value;
                    this.RaisePropertyChanged("MineralRich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MostlyWater {
            get {
                return this.MostlyWaterField;
            }
            set {
                if ((this.MostlyWaterField.Equals(value) != true)) {
                    this.MostlyWaterField = value;
                    this.RaisePropertyChanged("MostlyWater");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UninverseWcf.IUniverse")]
    public interface IUniverse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GetUniversePortion", ReplyAction="http://tempuri.org/IUniverse/GetUniversePortionResponse")]
        WcfTester.UninverseWcf.StarDto[] GetUniversePortion(WcfTester.UninverseWcf.UniverseRangeDto universeRage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GetUniversePortion", ReplyAction="http://tempuri.org/IUniverse/GetUniversePortionResponse")]
        System.Threading.Tasks.Task<WcfTester.UninverseWcf.StarDto[]> GetUniversePortionAsync(WcfTester.UninverseWcf.UniverseRangeDto universeRage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveUniversePortion", ReplyAction="http://tempuri.org/IUniverse/RetrieveUniversePortionResponse")]
        string RetrieveUniversePortion(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/RetrieveUniversePortion", ReplyAction="http://tempuri.org/IUniverse/RetrieveUniversePortionResponse")]
        System.Threading.Tasks.Task<string> RetrieveUniversePortionAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GenerateStarSystem", ReplyAction="http://tempuri.org/IUniverse/GenerateStarSystemResponse")]
        string GenerateStarSystem(WcfTester.UninverseWcf.PlanetGenerationDto generationData, string hashcall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniverse/GenerateStarSystem", ReplyAction="http://tempuri.org/IUniverse/GenerateStarSystemResponse")]
        System.Threading.Tasks.Task<string> GenerateStarSystemAsync(WcfTester.UninverseWcf.PlanetGenerationDto generationData, string hashcall);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUniverseChannel : WcfTester.UninverseWcf.IUniverse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniverseClient : System.ServiceModel.ClientBase<WcfTester.UninverseWcf.IUniverse>, WcfTester.UninverseWcf.IUniverse {
        
        public UniverseClient() {
        }
        
        public UniverseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniverseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniverseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniverseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfTester.UninverseWcf.StarDto[] GetUniversePortion(WcfTester.UninverseWcf.UniverseRangeDto universeRage) {
            return base.Channel.GetUniversePortion(universeRage);
        }
        
        public System.Threading.Tasks.Task<WcfTester.UninverseWcf.StarDto[]> GetUniversePortionAsync(WcfTester.UninverseWcf.UniverseRangeDto universeRage) {
            return base.Channel.GetUniversePortionAsync(universeRage);
        }
        
        public string RetrieveUniversePortion(string data) {
            return base.Channel.RetrieveUniversePortion(data);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveUniversePortionAsync(string data) {
            return base.Channel.RetrieveUniversePortionAsync(data);
        }
        
        public string GenerateStarSystem(WcfTester.UninverseWcf.PlanetGenerationDto generationData, string hashcall) {
            return base.Channel.GenerateStarSystem(generationData, hashcall);
        }
        
        public System.Threading.Tasks.Task<string> GenerateStarSystemAsync(WcfTester.UninverseWcf.PlanetGenerationDto generationData, string hashcall) {
            return base.Channel.GenerateStarSystemAsync(generationData, hashcall);
        }
    }
}
